name: Money4Mobs
<<<<<<< HEAD
version: 1.3.3
=======
version: 1.3.2b
>>>>>>> 8e5ee28eab6f7003a1713d449bfe25f2cc057efc
author: Latch
main: Latch.Money4Mobs.Money4Mobs
api-version: 1.16
softdepend: [Vault]
commands:
  mk:
    description: Mob Killer
    usage: /mk
  enc:
    description: Enchants
    usage: /enc
    permission: m4m.command.enc