name: DutchmanMiniGames
version: 0.0.1
author: Latch
main: Latch.DutchmanMiniGames.DutchmanMiniGames
api-version: 1.17
softdepend: [Vault]
commands:
  tickets:
    description: Check for amount of tickets
    usage: /tickets
  dutchman:
    description: Main command
    usage: /dutchman reload