name: Money4Mobs
version: 1.3.0a
author: Latch
main: Latch.Money4Mobs.Money4Mobs
api-version: 1.16
softdepend: [Vault]
commands:
  mk:
    description: Mob Killer
    usage: /mk
  enc:
    description: Enchants
    usage: /enc
    permission: m4m.command.enc